// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]

use wasmlib::*;

use crate::*;

pub(crate) const IDX_PARAM_DECLARATION_TYPE : usize = 0;
pub(crate) const IDX_PARAM_IDENTIFIER       : usize = 1;
pub(crate) const IDX_PARAM_OBJECT_HASH      : usize = 2;
pub(crate) const IDX_PARAM_OWNER            : usize = 3;
pub(crate) const IDX_PARAM_PUBLIC_KEY       : usize = 4;
pub(crate) const IDX_PARAM_SIGNATURE        : usize = 5;
pub(crate) const IDX_PARAM_SIGNOR_HASH      : usize = 6;
pub(crate) const IDX_PARAM_VALIDATION_URL   : usize = 7;

pub(crate) const IDX_RESULT_DECLARATIONS    : usize = 8;
pub(crate) const IDX_RESULT_IDENTITY_CLAIMS : usize = 9;
pub(crate) const IDX_RESULT_INFO            : usize = 10;
pub(crate) const IDX_RESULT_OWNER           : usize = 11;

pub(crate) const IDX_STATE_DECLARATIONS    : usize = 12;
pub(crate) const IDX_STATE_IDENTITY_CLAIMS : usize = 13;
pub(crate) const IDX_STATE_OWNER           : usize = 14;

pub const KEY_MAP_LEN: usize = 15;

pub const KEY_MAP: [&str; KEY_MAP_LEN] = [
	PARAM_DECLARATION_TYPE,
	PARAM_IDENTIFIER,
	PARAM_OBJECT_HASH,
	PARAM_OWNER,
	PARAM_PUBLIC_KEY,
	PARAM_SIGNATURE,
	PARAM_SIGNOR_HASH,
	PARAM_VALIDATION_URL,
	RESULT_DECLARATIONS,
	RESULT_IDENTITY_CLAIMS,
	RESULT_INFO,
	RESULT_OWNER,
	STATE_DECLARATIONS,
	STATE_IDENTITY_CLAIMS,
	STATE_OWNER,
];

pub static mut IDX_MAP: [Key32; KEY_MAP_LEN] = [Key32(0); KEY_MAP_LEN];

pub fn idx_map(idx: usize) -> Key32 {
    unsafe {
        IDX_MAP[idx]
    }
}
