// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]
#![allow(unused_mut)]

use wasmlib::*;

pub struct gotnewEvents {
}

impl gotnewEvents {

	pub fn declaration_created(&self, declaration_type: &str, object_hash: &ScHash, signature: &str, signor_hash: &ScHash, timestamp: i64, transaction_hash: &ScHash) {
		let mut evt = EventEncoder::new("gotnew.declarationCreated");
		evt.encode(&string_to_string(&declaration_type));
		evt.encode(&hash_to_string(&object_hash));
		evt.encode(&string_to_string(&signature));
		evt.encode(&hash_to_string(&signor_hash));
		evt.encode(&int64_to_string(timestamp));
		evt.encode(&hash_to_string(&transaction_hash));
		evt.emit();
	}

	pub fn identity_claim_created(&self, identifier: &str, public_key: &str, signature: &str, timestamp: i64, transaction_hash: &ScHash, validation_url: &str) {
		let mut evt = EventEncoder::new("gotnew.identityClaimCreated");
		evt.encode(&string_to_string(&identifier));
		evt.encode(&string_to_string(&public_key));
		evt.encode(&string_to_string(&signature));
		evt.encode(&int64_to_string(timestamp));
		evt.encode(&hash_to_string(&transaction_hash));
		evt.encode(&string_to_string(&validation_url));
		evt.emit();
	}
}
