// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]
#![allow(unused_imports)]

use gotnew::*;
use wasmlib::*;

use crate::consts::*;
use crate::events::*;
use crate::params::*;
use crate::results::*;
use crate::state::*;
use crate::structs::*;

mod consts;
mod contract;
mod events;
mod params;
mod results;
mod state;
mod structs;

mod gotnew;

const EXPORT_MAP: ScExportMap = ScExportMap {
    names: &[
    	FUNC_CREATE_DECLARATION,
    	FUNC_CREATE_IDENTITY_CLAIM,
    	FUNC_INIT,
    	FUNC_SET_OWNER,
    	VIEW_GET_DECLARATIONS,
    	VIEW_GET_GRAPH_OF_TRUST_INFO,
    	VIEW_GET_IDENTITY_CLAIMS,
    	VIEW_GET_OWNER,
	],
    funcs: &[
    	func_create_declaration_thunk,
    	func_create_identity_claim_thunk,
    	func_init_thunk,
    	func_set_owner_thunk,
	],
    views: &[
    	view_get_declarations_thunk,
    	view_get_graph_of_trust_info_thunk,
    	view_get_identity_claims_thunk,
    	view_get_owner_thunk,
	],
};

#[no_mangle]
fn on_call(index: i32) {
	ScExports::call(index, &EXPORT_MAP);
}

#[no_mangle]
fn on_load() {
    ScExports::export(&EXPORT_MAP);
}

pub struct CreateDeclarationContext {
	events:  gotnewEvents,
	params: ImmutableCreateDeclarationParams,
	state: MutablegotnewState,
}

fn func_create_declaration_thunk(ctx: &ScFuncContext) {
	ctx.log("gotnew.funcCreateDeclaration");
	let f = CreateDeclarationContext {
		events:  gotnewEvents {},
		params: ImmutableCreateDeclarationParams { proxy: params_proxy() },
		state: MutablegotnewState { proxy: state_proxy() },
	};
	ctx.require(f.params.declaration_type().exists(), "missing mandatory declarationType");
	ctx.require(f.params.object_hash().exists(), "missing mandatory objectHash");
	ctx.require(f.params.signature().exists(), "missing mandatory signature");
	ctx.require(f.params.signor_hash().exists(), "missing mandatory signorHash");
	func_create_declaration(ctx, &f);
	ctx.log("gotnew.funcCreateDeclaration ok");
}

pub struct CreateIdentityClaimContext {
	events:  gotnewEvents,
	params: ImmutableCreateIdentityClaimParams,
	state: MutablegotnewState,
}

fn func_create_identity_claim_thunk(ctx: &ScFuncContext) {
	ctx.log("gotnew.funcCreateIdentityClaim");
	let f = CreateIdentityClaimContext {
		events:  gotnewEvents {},
		params: ImmutableCreateIdentityClaimParams { proxy: params_proxy() },
		state: MutablegotnewState { proxy: state_proxy() },
	};
	ctx.require(f.params.identifier().exists(), "missing mandatory identifier");
	ctx.require(f.params.public_key().exists(), "missing mandatory publicKey");
	ctx.require(f.params.signature().exists(), "missing mandatory signature");
	ctx.require(f.params.validation_url().exists(), "missing mandatory validationUrl");
	func_create_identity_claim(ctx, &f);
	ctx.log("gotnew.funcCreateIdentityClaim ok");
}

pub struct InitContext {
	events:  gotnewEvents,
	params: ImmutableInitParams,
	state: MutablegotnewState,
}

fn func_init_thunk(ctx: &ScFuncContext) {
	ctx.log("gotnew.funcInit");
	let f = InitContext {
		events:  gotnewEvents {},
		params: ImmutableInitParams { proxy: params_proxy() },
		state: MutablegotnewState { proxy: state_proxy() },
	};
	func_init(ctx, &f);
	ctx.log("gotnew.funcInit ok");
}

pub struct SetOwnerContext {
	events:  gotnewEvents,
	params: ImmutableSetOwnerParams,
	state: MutablegotnewState,
}

fn func_set_owner_thunk(ctx: &ScFuncContext) {
	ctx.log("gotnew.funcSetOwner");
	let f = SetOwnerContext {
		events:  gotnewEvents {},
		params: ImmutableSetOwnerParams { proxy: params_proxy() },
		state: MutablegotnewState { proxy: state_proxy() },
	};

	// current owner of this smart contract
	let access = f.state.owner();
	ctx.require(access.exists(), "access not set: owner");
	ctx.require(ctx.caller() == access.value(), "no permission");

	ctx.require(f.params.owner().exists(), "missing mandatory owner");
	func_set_owner(ctx, &f);
	ctx.log("gotnew.funcSetOwner ok");
}

pub struct GetDeclarationsContext {
	results: MutableGetDeclarationsResults,
	state: ImmutablegotnewState,
}

fn view_get_declarations_thunk(ctx: &ScViewContext) {
	ctx.log("gotnew.viewGetDeclarations");
	let f = GetDeclarationsContext {
		results: MutableGetDeclarationsResults { proxy: results_proxy() },
		state: ImmutablegotnewState { proxy: state_proxy() },
	};
	view_get_declarations(ctx, &f);
	ctx.results(&f.results.proxy.kv_store);
	ctx.log("gotnew.viewGetDeclarations ok");
}

pub struct GetGraphOfTrustInfoContext {
	results: MutableGetGraphOfTrustInfoResults,
	state: ImmutablegotnewState,
}

fn view_get_graph_of_trust_info_thunk(ctx: &ScViewContext) {
	ctx.log("gotnew.viewGetGraphOfTrustInfo");
	let f = GetGraphOfTrustInfoContext {
		results: MutableGetGraphOfTrustInfoResults { proxy: results_proxy() },
		state: ImmutablegotnewState { proxy: state_proxy() },
	};
	view_get_graph_of_trust_info(ctx, &f);
	ctx.results(&f.results.proxy.kv_store);
	ctx.log("gotnew.viewGetGraphOfTrustInfo ok");
}

pub struct GetIdentityClaimsContext {
	results: MutableGetIdentityClaimsResults,
	state: ImmutablegotnewState,
}

fn view_get_identity_claims_thunk(ctx: &ScViewContext) {
	ctx.log("gotnew.viewGetIdentityClaims");
	let f = GetIdentityClaimsContext {
		results: MutableGetIdentityClaimsResults { proxy: results_proxy() },
		state: ImmutablegotnewState { proxy: state_proxy() },
	};
	view_get_identity_claims(ctx, &f);
	ctx.results(&f.results.proxy.kv_store);
	ctx.log("gotnew.viewGetIdentityClaims ok");
}

pub struct GetOwnerContext {
	results: MutableGetOwnerResults,
	state: ImmutablegotnewState,
}

fn view_get_owner_thunk(ctx: &ScViewContext) {
	ctx.log("gotnew.viewGetOwner");
	let f = GetOwnerContext {
		results: MutableGetOwnerResults { proxy: results_proxy() },
		state: ImmutablegotnewState { proxy: state_proxy() },
	};
	view_get_owner(ctx, &f);
	ctx.results(&f.results.proxy.kv_store);
	ctx.log("gotnew.viewGetOwner ok");
}
