// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]

use wasmlib::*;

pub const SC_NAME        : &str = "graphoftrust";
pub const SC_DESCRIPTION : &str = "The Graph of Trust is a distributed public key infrastructure";
pub const HSC_NAME       : ScHname = ScHname(0xf215bcfd);

pub const PARAM_DECLARATION_TYPE : &str = "declarationType";
pub const PARAM_IDENTIFIER       : &str = "identifier";
pub const PARAM_OBJECT_HASH      : &str = "objectHash";
pub const PARAM_OWNER            : &str = "owner";
pub const PARAM_PUBLIC_KEY       : &str = "publicKey";
pub const PARAM_SIGNATURE        : &str = "signature";
pub const PARAM_SIGNOR_HASH      : &str = "signorHash";
pub const PARAM_VALIDATION_URL   : &str = "validationUrl";

pub const RESULT_DECLARATIONS    : &str = "declarations";
pub const RESULT_IDENTITY_CLAIMS : &str = "identityClaims";
pub const RESULT_INFO            : &str = "info";
pub const RESULT_OWNER           : &str = "owner";

pub const STATE_DECLARATIONS    : &str = "declarations";
pub const STATE_IDENTITY_CLAIMS : &str = "identityClaims";
pub const STATE_OWNER           : &str = "owner";

pub const FUNC_CREATE_DECLARATION      : &str = "createDeclaration";
pub const FUNC_CREATE_IDENTITY_CLAIM   : &str = "createIdentityClaim";
pub const FUNC_INIT                    : &str = "init";
pub const FUNC_SET_OWNER               : &str = "setOwner";
pub const VIEW_GET_DECLARATIONS        : &str = "getDeclarations";
pub const VIEW_GET_GRAPH_OF_TRUST_INFO : &str = "getGraphOfTrustInfo";
pub const VIEW_GET_IDENTITY_CLAIMS     : &str = "getIdentityClaims";
pub const VIEW_GET_OWNER               : &str = "getOwner";

pub const HFUNC_CREATE_DECLARATION      : ScHname = ScHname(0x6616650a);
pub const HFUNC_CREATE_IDENTITY_CLAIM   : ScHname = ScHname(0xe5cc8879);
pub const HFUNC_INIT                    : ScHname = ScHname(0x1f44d644);
pub const HFUNC_SET_OWNER               : ScHname = ScHname(0x2a15fe7b);
pub const HVIEW_GET_DECLARATIONS        : ScHname = ScHname(0x23c12c89);
pub const HVIEW_GET_GRAPH_OF_TRUST_INFO : ScHname = ScHname(0xfa353efc);
pub const HVIEW_GET_IDENTITY_CLAIMS     : ScHname = ScHname(0xb86c8ea9);
pub const HVIEW_GET_OWNER               : ScHname = ScHname(0x137107a6);
