// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]
#![allow(unused_imports)]

use wasmlib::*;

use crate::*;

#[derive(Clone)]
pub struct MapHashToImmutableDeclaration {
	pub(crate) proxy: Proxy,
}

impl MapHashToImmutableDeclaration {
    pub fn get_declaration(&self, key: &ScHash) -> ImmutableDeclaration {
        ImmutableDeclaration { proxy: self.proxy.key(&hash_to_bytes(key)) }
    }
}

#[derive(Clone)]
pub struct MapHashToImmutableIdentityClaim {
	pub(crate) proxy: Proxy,
}

impl MapHashToImmutableIdentityClaim {
    pub fn get_identity_claim(&self, key: &ScHash) -> ImmutableIdentityClaim {
        ImmutableIdentityClaim { proxy: self.proxy.key(&hash_to_bytes(key)) }
    }
}

#[derive(Clone)]
pub struct ImmutableGraphOfTrustState {
	pub(crate) proxy: Proxy,
}

impl ImmutableGraphOfTrustState {
    pub fn declarations(&self) -> MapHashToImmutableDeclaration {
		MapHashToImmutableDeclaration { proxy: self.proxy.root(STATE_DECLARATIONS) }
	}

    pub fn identity_claims(&self) -> MapHashToImmutableIdentityClaim {
		MapHashToImmutableIdentityClaim { proxy: self.proxy.root(STATE_IDENTITY_CLAIMS) }
	}

    pub fn owner(&self) -> ScImmutableAgentID {
		ScImmutableAgentID::new(self.proxy.root(STATE_OWNER))
	}
}

#[derive(Clone)]
pub struct MapHashToMutableDeclaration {
	pub(crate) proxy: Proxy,
}

impl MapHashToMutableDeclaration {
    pub fn clear(&self) {
        self.proxy.clear_map();
    }

    pub fn get_declaration(&self, key: &ScHash) -> MutableDeclaration {
        MutableDeclaration { proxy: self.proxy.key(&hash_to_bytes(key)) }
    }
}

#[derive(Clone)]
pub struct MapHashToMutableIdentityClaim {
	pub(crate) proxy: Proxy,
}

impl MapHashToMutableIdentityClaim {
    pub fn clear(&self) {
        self.proxy.clear_map();
    }

    pub fn get_identity_claim(&self, key: &ScHash) -> MutableIdentityClaim {
        MutableIdentityClaim { proxy: self.proxy.key(&hash_to_bytes(key)) }
    }
}

#[derive(Clone)]
pub struct MutableGraphOfTrustState {
	pub(crate) proxy: Proxy,
}

impl MutableGraphOfTrustState {
    pub fn as_immutable(&self) -> ImmutableGraphOfTrustState {
		ImmutableGraphOfTrustState { proxy: self.proxy.root("") }
	}

    pub fn declarations(&self) -> MapHashToMutableDeclaration {
		MapHashToMutableDeclaration { proxy: self.proxy.root(STATE_DECLARATIONS) }
	}

    pub fn identity_claims(&self) -> MapHashToMutableIdentityClaim {
		MapHashToMutableIdentityClaim { proxy: self.proxy.root(STATE_IDENTITY_CLAIMS) }
	}

    pub fn owner(&self) -> ScMutableAgentID {
		ScMutableAgentID::new(self.proxy.root(STATE_OWNER))
	}
}
