// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]
#![allow(unused_imports)]

use wasmlib::*;

#[derive(Clone)]
pub struct Declaration {
    pub declaration_type : String, 
    pub object_hash      : ScHash, 
    pub signature        : String, 
    pub signor_hash      : ScHash, 
    pub timestamp        : i64, 
    pub transaction_hash : ScHash, 
}

impl Declaration {
    pub fn from_bytes(bytes: &[u8]) -> Declaration {
        let mut dec = WasmDecoder::new(bytes);
        Declaration {
            declaration_type : string_decode(&mut dec),
            object_hash      : hash_decode(&mut dec),
            signature        : string_decode(&mut dec),
            signor_hash      : hash_decode(&mut dec),
            timestamp        : int64_decode(&mut dec),
            transaction_hash : hash_decode(&mut dec),
        }
    }

    pub fn to_bytes(&self) -> Vec<u8> {
        let mut enc = WasmEncoder::new();
		string_encode(&mut enc, &self.declaration_type);
		hash_encode(&mut enc, &self.object_hash);
		string_encode(&mut enc, &self.signature);
		hash_encode(&mut enc, &self.signor_hash);
		int64_encode(&mut enc, self.timestamp);
		hash_encode(&mut enc, &self.transaction_hash);
        enc.buf()
    }
}

#[derive(Clone)]
pub struct ImmutableDeclaration {
    pub(crate) proxy: Proxy,
}

impl ImmutableDeclaration {
    pub fn exists(&self) -> bool {
        self.proxy.exists()
    }

    pub fn value(&self) -> Declaration {
        Declaration::from_bytes(&self.proxy.get())
    }
}

#[derive(Clone)]
pub struct MutableDeclaration {
    pub(crate) proxy: Proxy,
}

impl MutableDeclaration {
    pub fn delete(&self) {
        self.proxy.delete();
    }

    pub fn exists(&self) -> bool {
        self.proxy.exists()
    }

    pub fn set_value(&self, value: &Declaration) {
        self.proxy.set(&value.to_bytes());
    }

    pub fn value(&self) -> Declaration {
        Declaration::from_bytes(&self.proxy.get())
    }
}

#[derive(Clone)]
pub struct IdentityClaim {
    pub identifier       : String, 
    pub public_key       : String, 
    pub signature        : String, 
    pub timestamp        : i64, 
    pub transaction_hash : ScHash, 
    pub validation_url   : String, 
}

impl IdentityClaim {
    pub fn from_bytes(bytes: &[u8]) -> IdentityClaim {
        let mut dec = WasmDecoder::new(bytes);
        IdentityClaim {
            identifier       : string_decode(&mut dec),
            public_key       : string_decode(&mut dec),
            signature        : string_decode(&mut dec),
            timestamp        : int64_decode(&mut dec),
            transaction_hash : hash_decode(&mut dec),
            validation_url   : string_decode(&mut dec),
        }
    }

    pub fn to_bytes(&self) -> Vec<u8> {
        let mut enc = WasmEncoder::new();
		string_encode(&mut enc, &self.identifier);
		string_encode(&mut enc, &self.public_key);
		string_encode(&mut enc, &self.signature);
		int64_encode(&mut enc, self.timestamp);
		hash_encode(&mut enc, &self.transaction_hash);
		string_encode(&mut enc, &self.validation_url);
        enc.buf()
    }
}

#[derive(Clone)]
pub struct ImmutableIdentityClaim {
    pub(crate) proxy: Proxy,
}

impl ImmutableIdentityClaim {
    pub fn exists(&self) -> bool {
        self.proxy.exists()
    }

    pub fn value(&self) -> IdentityClaim {
        IdentityClaim::from_bytes(&self.proxy.get())
    }
}

#[derive(Clone)]
pub struct MutableIdentityClaim {
    pub(crate) proxy: Proxy,
}

impl MutableIdentityClaim {
    pub fn delete(&self) {
        self.proxy.delete();
    }

    pub fn exists(&self) -> bool {
        self.proxy.exists()
    }

    pub fn set_value(&self, value: &IdentityClaim) {
        self.proxy.set(&value.to_bytes());
    }

    pub fn value(&self) -> IdentityClaim {
        IdentityClaim::from_bytes(&self.proxy.get())
    }
}
