// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package gotnew

import "github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"

const (
	ScName        = "gotnew"
	ScDescription = "The Graph of Trust is a distributed public key infrastructure"
	HScName       = wasmtypes.ScHname(0x05f5723a)
)

const (
	ParamDeclarationType = "declarationType"
	ParamIdentifier      = "identifier"
	ParamObjectHash      = "objectHash"
	ParamOwner           = "owner"
	ParamPublicKey       = "publicKey"
	ParamSignature       = "signature"
	ParamSignorHash      = "signorHash"
	ParamValidationUrl   = "validationUrl"
)

const (
	ResultDeclarations   = "declarations"
	ResultIdentityClaims = "identityClaims"
	ResultInfo           = "info"
	ResultOwner          = "owner"
)

const (
	StateDeclarations   = "declarations"
	StateIdentityClaims = "identityClaims"
	StateOwner          = "owner"
)

const (
	FuncCreateDeclaration   = "createDeclaration"
	FuncCreateIdentityClaim = "createIdentityClaim"
	FuncInit                = "init"
	FuncSetOwner            = "setOwner"
	ViewGetDeclarations     = "getDeclarations"
	ViewGetGraphOfTrustInfo = "getGraphOfTrustInfo"
	ViewGetIdentityClaims   = "getIdentityClaims"
	ViewGetOwner            = "getOwner"
)

const (
	HFuncCreateDeclaration   = wasmtypes.ScHname(0x6616650a)
	HFuncCreateIdentityClaim = wasmtypes.ScHname(0xe5cc8879)
	HFuncInit                = wasmtypes.ScHname(0x1f44d644)
	HFuncSetOwner            = wasmtypes.ScHname(0x2a15fe7b)
	HViewGetDeclarations     = wasmtypes.ScHname(0x23c12c89)
	HViewGetGraphOfTrustInfo = wasmtypes.ScHname(0xfa353efc)
	HViewGetIdentityClaims   = wasmtypes.ScHname(0xb86c8ea9)
	HViewGetOwner            = wasmtypes.ScHname(0x137107a6)
)
