// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package gotnew

import "github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib"

type CreateDeclarationCall struct {
	Func    *wasmlib.ScFunc
	Params  MutableCreateDeclarationParams
}

type CreateIdentityClaimCall struct {
	Func    *wasmlib.ScFunc
	Params  MutableCreateIdentityClaimParams
}

type InitCall struct {
	Func    *wasmlib.ScInitFunc
	Params  MutableInitParams
}

type SetOwnerCall struct {
	Func    *wasmlib.ScFunc
	Params  MutableSetOwnerParams
}

type GetDeclarationsCall struct {
	Func    *wasmlib.ScView
	Results ImmutableGetDeclarationsResults
}

type GetGraphOfTrustInfoCall struct {
	Func    *wasmlib.ScView
	Results ImmutableGetGraphOfTrustInfoResults
}

type GetIdentityClaimsCall struct {
	Func    *wasmlib.ScView
	Results ImmutableGetIdentityClaimsResults
}

type GetOwnerCall struct {
	Func    *wasmlib.ScView
	Results ImmutableGetOwnerResults
}

type Funcs struct{}

var ScFuncs Funcs

func (sc Funcs) CreateDeclaration(ctx wasmlib.ScFuncCallContext) *CreateDeclarationCall {
	f := &CreateDeclarationCall{Func: wasmlib.NewScFunc(ctx, HScName, HFuncCreateDeclaration)}
	f.Params.proxy = wasmlib.NewCallParamsProxy(&f.Func.ScView)
	return f
}

func (sc Funcs) CreateIdentityClaim(ctx wasmlib.ScFuncCallContext) *CreateIdentityClaimCall {
	f := &CreateIdentityClaimCall{Func: wasmlib.NewScFunc(ctx, HScName, HFuncCreateIdentityClaim)}
	f.Params.proxy = wasmlib.NewCallParamsProxy(&f.Func.ScView)
	return f
}

func (sc Funcs) Init(ctx wasmlib.ScFuncCallContext) *InitCall {
	f := &InitCall{Func: wasmlib.NewScInitFunc(ctx, HScName, HFuncInit)}
	f.Params.proxy = wasmlib.NewCallParamsProxy(&f.Func.ScView)
	return f
}

func (sc Funcs) SetOwner(ctx wasmlib.ScFuncCallContext) *SetOwnerCall {
	f := &SetOwnerCall{Func: wasmlib.NewScFunc(ctx, HScName, HFuncSetOwner)}
	f.Params.proxy = wasmlib.NewCallParamsProxy(&f.Func.ScView)
	return f
}

func (sc Funcs) GetDeclarations(ctx wasmlib.ScViewCallContext) *GetDeclarationsCall {
	f := &GetDeclarationsCall{Func: wasmlib.NewScView(ctx, HScName, HViewGetDeclarations)}
	wasmlib.NewCallResultsProxy(f.Func, &f.Results.proxy)
	return f
}

func (sc Funcs) GetGraphOfTrustInfo(ctx wasmlib.ScViewCallContext) *GetGraphOfTrustInfoCall {
	f := &GetGraphOfTrustInfoCall{Func: wasmlib.NewScView(ctx, HScName, HViewGetGraphOfTrustInfo)}
	wasmlib.NewCallResultsProxy(f.Func, &f.Results.proxy)
	return f
}

func (sc Funcs) GetIdentityClaims(ctx wasmlib.ScViewCallContext) *GetIdentityClaimsCall {
	f := &GetIdentityClaimsCall{Func: wasmlib.NewScView(ctx, HScName, HViewGetIdentityClaims)}
	wasmlib.NewCallResultsProxy(f.Func, &f.Results.proxy)
	return f
}

func (sc Funcs) GetOwner(ctx wasmlib.ScViewCallContext) *GetOwnerCall {
	f := &GetOwnerCall{Func: wasmlib.NewScView(ctx, HScName, HViewGetOwner)}
	wasmlib.NewCallResultsProxy(f.Func, &f.Results.proxy)
	return f
}
