// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

//nolint:gocritic
package gotnew

import "github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib"
import "github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"

type gotnewEvents struct {
}

func (e gotnewEvents) DeclarationCreated(declarationType string, objectHash wasmtypes.ScHash, signature string, signorHash wasmtypes.ScHash, timestamp int64, transactionHash wasmtypes.ScHash) {
	evt := wasmlib.NewEventEncoder("gotnew.declarationCreated")
	evt.Encode(wasmtypes.StringToString(declarationType))
	evt.Encode(wasmtypes.HashToString(objectHash))
	evt.Encode(wasmtypes.StringToString(signature))
	evt.Encode(wasmtypes.HashToString(signorHash))
	evt.Encode(wasmtypes.Int64ToString(timestamp))
	evt.Encode(wasmtypes.HashToString(transactionHash))
	evt.Emit()
}

func (e gotnewEvents) IdentityClaimCreated(identifier string, publicKey string, signature string, timestamp int64, transactionHash wasmtypes.ScHash, validationUrl string) {
	evt := wasmlib.NewEventEncoder("gotnew.identityClaimCreated")
	evt.Encode(wasmtypes.StringToString(identifier))
	evt.Encode(wasmtypes.StringToString(publicKey))
	evt.Encode(wasmtypes.StringToString(signature))
	evt.Encode(wasmtypes.Int64ToString(timestamp))
	evt.Encode(wasmtypes.HashToString(transactionHash))
	evt.Encode(wasmtypes.StringToString(validationUrl))
	evt.Emit()
}
