// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

//nolint:dupl
package gotnew

import "github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib"

var exportMap = wasmlib.ScExportMap{
	Names: []string{
    	FuncCreateDeclaration,
    	FuncCreateIdentityClaim,
    	FuncInit,
    	FuncSetOwner,
    	ViewGetDeclarations,
    	ViewGetGraphOfTrustInfo,
    	ViewGetIdentityClaims,
    	ViewGetOwner,
	},
	Funcs: []wasmlib.ScFuncContextFunction{
    	funcCreateDeclarationThunk,
    	funcCreateIdentityClaimThunk,
    	funcInitThunk,
    	funcSetOwnerThunk,
	},
	Views: []wasmlib.ScViewContextFunction{
    	viewGetDeclarationsThunk,
    	viewGetGraphOfTrustInfoThunk,
    	viewGetIdentityClaimsThunk,
    	viewGetOwnerThunk,
	},
}

func OnLoad(index int32) {
	if index >= 0 {
		wasmlib.ScExportsCall(index, &exportMap)
		return
	}

	wasmlib.ScExportsExport(&exportMap)
}

type CreateDeclarationContext struct {
	Events  gotnewEvents
	Params  ImmutableCreateDeclarationParams
	State   MutablegotnewState
}

func funcCreateDeclarationThunk(ctx wasmlib.ScFuncContext) {
	ctx.Log("gotnew.funcCreateDeclaration")
	f := &CreateDeclarationContext{
		Params: ImmutableCreateDeclarationParams{
			proxy: wasmlib.NewParamsProxy(),
		},
		State: MutablegotnewState{
			proxy: wasmlib.NewStateProxy(),
		},
	}
	ctx.Require(f.Params.DeclarationType().Exists(), "missing mandatory declarationType")
	ctx.Require(f.Params.ObjectHash().Exists(), "missing mandatory objectHash")
	ctx.Require(f.Params.Signature().Exists(), "missing mandatory signature")
	ctx.Require(f.Params.SignorHash().Exists(), "missing mandatory signorHash")
	funcCreateDeclaration(ctx, f)
	ctx.Log("gotnew.funcCreateDeclaration ok")
}

type CreateIdentityClaimContext struct {
	Events  gotnewEvents
	Params  ImmutableCreateIdentityClaimParams
	State   MutablegotnewState
}

func funcCreateIdentityClaimThunk(ctx wasmlib.ScFuncContext) {
	ctx.Log("gotnew.funcCreateIdentityClaim")
	f := &CreateIdentityClaimContext{
		Params: ImmutableCreateIdentityClaimParams{
			proxy: wasmlib.NewParamsProxy(),
		},
		State: MutablegotnewState{
			proxy: wasmlib.NewStateProxy(),
		},
	}
	ctx.Require(f.Params.Identifier().Exists(), "missing mandatory identifier")
	ctx.Require(f.Params.PublicKey().Exists(), "missing mandatory publicKey")
	ctx.Require(f.Params.Signature().Exists(), "missing mandatory signature")
	ctx.Require(f.Params.ValidationUrl().Exists(), "missing mandatory validationUrl")
	funcCreateIdentityClaim(ctx, f)
	ctx.Log("gotnew.funcCreateIdentityClaim ok")
}

type InitContext struct {
	Events  gotnewEvents
	Params  ImmutableInitParams
	State   MutablegotnewState
}

func funcInitThunk(ctx wasmlib.ScFuncContext) {
	ctx.Log("gotnew.funcInit")
	f := &InitContext{
		Params: ImmutableInitParams{
			proxy: wasmlib.NewParamsProxy(),
		},
		State: MutablegotnewState{
			proxy: wasmlib.NewStateProxy(),
		},
	}
	funcInit(ctx, f)
	ctx.Log("gotnew.funcInit ok")
}

type SetOwnerContext struct {
	Events  gotnewEvents
	Params  ImmutableSetOwnerParams
	State   MutablegotnewState
}

func funcSetOwnerThunk(ctx wasmlib.ScFuncContext) {
	ctx.Log("gotnew.funcSetOwner")
	f := &SetOwnerContext{
		Params: ImmutableSetOwnerParams{
			proxy: wasmlib.NewParamsProxy(),
		},
		State: MutablegotnewState{
			proxy: wasmlib.NewStateProxy(),
		},
	}

	// current owner of this smart contract
	access := f.State.Owner()
	ctx.Require(access.Exists(), "access not set: owner")
	ctx.Require(ctx.Caller() == access.Value(), "no permission")

	ctx.Require(f.Params.Owner().Exists(), "missing mandatory owner")
	funcSetOwner(ctx, f)
	ctx.Log("gotnew.funcSetOwner ok")
}

type GetDeclarationsContext struct {
	Results MutableGetDeclarationsResults
	State   ImmutablegotnewState
}

func viewGetDeclarationsThunk(ctx wasmlib.ScViewContext) {
	ctx.Log("gotnew.viewGetDeclarations")
	results := wasmlib.NewScDict()
	f := &GetDeclarationsContext{
		Results: MutableGetDeclarationsResults{
			proxy: results.AsProxy(),
		},
		State: ImmutablegotnewState{
			proxy: wasmlib.NewStateProxy(),
		},
	}
	viewGetDeclarations(ctx, f)
	ctx.Results(results)
	ctx.Log("gotnew.viewGetDeclarations ok")
}

type GetGraphOfTrustInfoContext struct {
	Results MutableGetGraphOfTrustInfoResults
	State   ImmutablegotnewState
}

func viewGetGraphOfTrustInfoThunk(ctx wasmlib.ScViewContext) {
	ctx.Log("gotnew.viewGetGraphOfTrustInfo")
	results := wasmlib.NewScDict()
	f := &GetGraphOfTrustInfoContext{
		Results: MutableGetGraphOfTrustInfoResults{
			proxy: results.AsProxy(),
		},
		State: ImmutablegotnewState{
			proxy: wasmlib.NewStateProxy(),
		},
	}
	viewGetGraphOfTrustInfo(ctx, f)
	ctx.Results(results)
	ctx.Log("gotnew.viewGetGraphOfTrustInfo ok")
}

type GetIdentityClaimsContext struct {
	Results MutableGetIdentityClaimsResults
	State   ImmutablegotnewState
}

func viewGetIdentityClaimsThunk(ctx wasmlib.ScViewContext) {
	ctx.Log("gotnew.viewGetIdentityClaims")
	results := wasmlib.NewScDict()
	f := &GetIdentityClaimsContext{
		Results: MutableGetIdentityClaimsResults{
			proxy: results.AsProxy(),
		},
		State: ImmutablegotnewState{
			proxy: wasmlib.NewStateProxy(),
		},
	}
	viewGetIdentityClaims(ctx, f)
	ctx.Results(results)
	ctx.Log("gotnew.viewGetIdentityClaims ok")
}

type GetOwnerContext struct {
	Results MutableGetOwnerResults
	State   ImmutablegotnewState
}

func viewGetOwnerThunk(ctx wasmlib.ScViewContext) {
	ctx.Log("gotnew.viewGetOwner")
	results := wasmlib.NewScDict()
	f := &GetOwnerContext{
		Results: MutableGetOwnerResults{
			proxy: results.AsProxy(),
		},
		State: ImmutablegotnewState{
			proxy: wasmlib.NewStateProxy(),
		},
	}
	viewGetOwner(ctx, f)
	ctx.Results(results)
	ctx.Log("gotnew.viewGetOwner ok")
}
