// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package gotnew

import "github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"

type ImmutableCreateDeclarationParams struct {
	proxy wasmtypes.Proxy
}

func (s ImmutableCreateDeclarationParams) DeclarationType() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.proxy.Root(ParamDeclarationType))
}

func (s ImmutableCreateDeclarationParams) ObjectHash() wasmtypes.ScImmutableHash {
	return wasmtypes.NewScImmutableHash(s.proxy.Root(ParamObjectHash))
}

func (s ImmutableCreateDeclarationParams) Signature() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.proxy.Root(ParamSignature))
}

func (s ImmutableCreateDeclarationParams) SignorHash() wasmtypes.ScImmutableHash {
	return wasmtypes.NewScImmutableHash(s.proxy.Root(ParamSignorHash))
}

type MutableCreateDeclarationParams struct {
	proxy wasmtypes.Proxy
}

func (s MutableCreateDeclarationParams) DeclarationType() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.proxy.Root(ParamDeclarationType))
}

func (s MutableCreateDeclarationParams) ObjectHash() wasmtypes.ScMutableHash {
	return wasmtypes.NewScMutableHash(s.proxy.Root(ParamObjectHash))
}

func (s MutableCreateDeclarationParams) Signature() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.proxy.Root(ParamSignature))
}

func (s MutableCreateDeclarationParams) SignorHash() wasmtypes.ScMutableHash {
	return wasmtypes.NewScMutableHash(s.proxy.Root(ParamSignorHash))
}

type ImmutableCreateIdentityClaimParams struct {
	proxy wasmtypes.Proxy
}

func (s ImmutableCreateIdentityClaimParams) Identifier() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.proxy.Root(ParamIdentifier))
}

func (s ImmutableCreateIdentityClaimParams) PublicKey() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.proxy.Root(ParamPublicKey))
}

func (s ImmutableCreateIdentityClaimParams) Signature() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.proxy.Root(ParamSignature))
}

func (s ImmutableCreateIdentityClaimParams) ValidationUrl() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.proxy.Root(ParamValidationUrl))
}

type MutableCreateIdentityClaimParams struct {
	proxy wasmtypes.Proxy
}

func (s MutableCreateIdentityClaimParams) Identifier() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.proxy.Root(ParamIdentifier))
}

func (s MutableCreateIdentityClaimParams) PublicKey() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.proxy.Root(ParamPublicKey))
}

func (s MutableCreateIdentityClaimParams) Signature() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.proxy.Root(ParamSignature))
}

func (s MutableCreateIdentityClaimParams) ValidationUrl() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.proxy.Root(ParamValidationUrl))
}

type ImmutableInitParams struct {
	proxy wasmtypes.Proxy
}

func (s ImmutableInitParams) Owner() wasmtypes.ScImmutableAgentID {
	return wasmtypes.NewScImmutableAgentID(s.proxy.Root(ParamOwner))
}

type MutableInitParams struct {
	proxy wasmtypes.Proxy
}

func (s MutableInitParams) Owner() wasmtypes.ScMutableAgentID {
	return wasmtypes.NewScMutableAgentID(s.proxy.Root(ParamOwner))
}

type ImmutableSetOwnerParams struct {
	proxy wasmtypes.Proxy
}

func (s ImmutableSetOwnerParams) Owner() wasmtypes.ScImmutableAgentID {
	return wasmtypes.NewScImmutableAgentID(s.proxy.Root(ParamOwner))
}

type MutableSetOwnerParams struct {
	proxy wasmtypes.Proxy
}

func (s MutableSetOwnerParams) Owner() wasmtypes.ScMutableAgentID {
	return wasmtypes.NewScMutableAgentID(s.proxy.Root(ParamOwner))
}
