// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package gotnew

import "github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"

type MapHashToImmutableDeclaration struct {
	proxy wasmtypes.Proxy
}

func (m MapHashToImmutableDeclaration) GetDeclaration(key wasmtypes.ScHash) ImmutableDeclaration {
	return ImmutableDeclaration{proxy: m.proxy.Key(wasmtypes.HashToBytes(key))}
}

type MapHashToImmutableIdentityClaim struct {
	proxy wasmtypes.Proxy
}

func (m MapHashToImmutableIdentityClaim) GetIdentityClaim(key wasmtypes.ScHash) ImmutableIdentityClaim {
	return ImmutableIdentityClaim{proxy: m.proxy.Key(wasmtypes.HashToBytes(key))}
}

type ImmutablegotnewState struct {
	proxy wasmtypes.Proxy
}

func (s ImmutablegotnewState) Declarations() MapHashToImmutableDeclaration {
	return MapHashToImmutableDeclaration{proxy: s.proxy.Root(StateDeclarations)}
}

func (s ImmutablegotnewState) IdentityClaims() MapHashToImmutableIdentityClaim {
	return MapHashToImmutableIdentityClaim{proxy: s.proxy.Root(StateIdentityClaims)}
}

func (s ImmutablegotnewState) Owner() wasmtypes.ScImmutableAgentID {
	return wasmtypes.NewScImmutableAgentID(s.proxy.Root(StateOwner))
}

type MapHashToMutableDeclaration struct {
	proxy wasmtypes.Proxy
}

func (m MapHashToMutableDeclaration) Clear() {
	m.proxy.ClearMap()
}

func (m MapHashToMutableDeclaration) GetDeclaration(key wasmtypes.ScHash) MutableDeclaration {
	return MutableDeclaration{proxy: m.proxy.Key(wasmtypes.HashToBytes(key))}
}

type MapHashToMutableIdentityClaim struct {
	proxy wasmtypes.Proxy
}

func (m MapHashToMutableIdentityClaim) Clear() {
	m.proxy.ClearMap()
}

func (m MapHashToMutableIdentityClaim) GetIdentityClaim(key wasmtypes.ScHash) MutableIdentityClaim {
	return MutableIdentityClaim{proxy: m.proxy.Key(wasmtypes.HashToBytes(key))}
}

type MutablegotnewState struct {
	proxy wasmtypes.Proxy
}

func (s MutablegotnewState) AsImmutable() ImmutablegotnewState {
	return ImmutablegotnewState(s)
}

func (s MutablegotnewState) Declarations() MapHashToMutableDeclaration {
	return MapHashToMutableDeclaration{proxy: s.proxy.Root(StateDeclarations)}
}

func (s MutablegotnewState) IdentityClaims() MapHashToMutableIdentityClaim {
	return MapHashToMutableIdentityClaim{proxy: s.proxy.Root(StateIdentityClaims)}
}

func (s MutablegotnewState) Owner() wasmtypes.ScMutableAgentID {
	return wasmtypes.NewScMutableAgentID(s.proxy.Root(StateOwner))
}
