// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package gotnew

import "github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"

type Declaration struct {
	DeclarationType string 
	ObjectHash      wasmtypes.ScHash 
	Signature       string 
	SignorHash      wasmtypes.ScHash 
	Timestamp       int64 
	TransactionHash wasmtypes.ScHash 
}

func NewDeclarationFromBytes(buf []byte) *Declaration {
	dec := wasmtypes.NewWasmDecoder(buf)
	data := &Declaration{}
	data.DeclarationType = wasmtypes.StringDecode(dec)
	data.ObjectHash      = wasmtypes.HashDecode(dec)
	data.Signature       = wasmtypes.StringDecode(dec)
	data.SignorHash      = wasmtypes.HashDecode(dec)
	data.Timestamp       = wasmtypes.Int64Decode(dec)
	data.TransactionHash = wasmtypes.HashDecode(dec)
	dec.Close()
	return data
}

func (o *Declaration) Bytes() []byte {
	enc := wasmtypes.NewWasmEncoder()
		wasmtypes.StringEncode(enc, o.DeclarationType)
		wasmtypes.HashEncode(enc, o.ObjectHash)
		wasmtypes.StringEncode(enc, o.Signature)
		wasmtypes.HashEncode(enc, o.SignorHash)
		wasmtypes.Int64Encode(enc, o.Timestamp)
		wasmtypes.HashEncode(enc, o.TransactionHash)
	return enc.Buf()
}

type ImmutableDeclaration struct {
	proxy wasmtypes.Proxy
}

func (o ImmutableDeclaration) Exists() bool {
	return o.proxy.Exists()
}

func (o ImmutableDeclaration) Value() *Declaration {
	return NewDeclarationFromBytes(o.proxy.Get())
}

type MutableDeclaration struct {
	proxy wasmtypes.Proxy
}

func (o MutableDeclaration) Delete() {
	o.proxy.Delete()
}

func (o MutableDeclaration) Exists() bool {
	return o.proxy.Exists()
}

func (o MutableDeclaration) SetValue(value *Declaration) {
	o.proxy.Set(value.Bytes())
}

func (o MutableDeclaration) Value() *Declaration {
	return NewDeclarationFromBytes(o.proxy.Get())
}

type IdentityClaim struct {
	Identifier      string 
	PublicKey       string 
	Signature       string 
	Timestamp       int64 
	TransactionHash wasmtypes.ScHash 
	ValidationUrl   string 
}

func NewIdentityClaimFromBytes(buf []byte) *IdentityClaim {
	dec := wasmtypes.NewWasmDecoder(buf)
	data := &IdentityClaim{}
	data.Identifier      = wasmtypes.StringDecode(dec)
	data.PublicKey       = wasmtypes.StringDecode(dec)
	data.Signature       = wasmtypes.StringDecode(dec)
	data.Timestamp       = wasmtypes.Int64Decode(dec)
	data.TransactionHash = wasmtypes.HashDecode(dec)
	data.ValidationUrl   = wasmtypes.StringDecode(dec)
	dec.Close()
	return data
}

func (o *IdentityClaim) Bytes() []byte {
	enc := wasmtypes.NewWasmEncoder()
		wasmtypes.StringEncode(enc, o.Identifier)
		wasmtypes.StringEncode(enc, o.PublicKey)
		wasmtypes.StringEncode(enc, o.Signature)
		wasmtypes.Int64Encode(enc, o.Timestamp)
		wasmtypes.HashEncode(enc, o.TransactionHash)
		wasmtypes.StringEncode(enc, o.ValidationUrl)
	return enc.Buf()
}

type ImmutableIdentityClaim struct {
	proxy wasmtypes.Proxy
}

func (o ImmutableIdentityClaim) Exists() bool {
	return o.proxy.Exists()
}

func (o ImmutableIdentityClaim) Value() *IdentityClaim {
	return NewIdentityClaimFromBytes(o.proxy.Get())
}

type MutableIdentityClaim struct {
	proxy wasmtypes.Proxy
}

func (o MutableIdentityClaim) Delete() {
	o.proxy.Delete()
}

func (o MutableIdentityClaim) Exists() bool {
	return o.proxy.Exists()
}

func (o MutableIdentityClaim) SetValue(value *IdentityClaim) {
	o.proxy.Set(value.Bytes())
}

func (o MutableIdentityClaim) Value() *IdentityClaim {
	return NewIdentityClaimFromBytes(o.proxy.Get())
}
