// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]
#![allow(unused_imports)]

use graphoftrust::*;
use wasmlib::*;

use crate::consts::*;
use crate::events::*;
use crate::params::*;
use crate::results::*;
use crate::state::*;
use crate::structs::*;

mod consts;
mod contract;
mod events;
mod params;
mod results;
mod state;
mod structs;

mod graphoftrust;

const EXPORT_MAP: ScExportMap = ScExportMap {
    names: &[
    	FUNC_CREATE_DECLARATION,
    	FUNC_CREATE_IDENTITY_CLAIM,
    	FUNC_INIT,
    	FUNC_SET_IDENTIFIER,
    	FUNC_SET_OWNER,
    	FUNC_SET_PUBLIC_KEY,
    	FUNC_SET_SIGNATURE,
    	FUNC_SET_VALIDATION_URL,
    	VIEW_GET_DECLARATIONS,
    	VIEW_GET_GRAPH_OF_TRUST_INFO,
    	VIEW_GET_IDENTITY_CLAIMS,
    	VIEW_GET_OWNER,
    	VIEW_GET_SIGNATURE_INFO,
	],
    funcs: &[
    	func_create_declaration_thunk,
    	func_create_identity_claim_thunk,
    	func_init_thunk,
    	func_set_identifier_thunk,
    	func_set_owner_thunk,
    	func_set_public_key_thunk,
    	func_set_signature_thunk,
    	func_set_validation_url_thunk,
	],
    views: &[
    	view_get_declarations_thunk,
    	view_get_graph_of_trust_info_thunk,
    	view_get_identity_claims_thunk,
    	view_get_owner_thunk,
    	view_get_signature_info_thunk,
	],
};

#[no_mangle]
fn on_call(index: i32) {
	ScExports::call(index, &EXPORT_MAP);
}

#[no_mangle]
fn on_load() {
    ScExports::export(&EXPORT_MAP);
}

pub struct CreateDeclarationContext {
	events:  GraphOfTrustEvents,
	params: ImmutableCreateDeclarationParams,
	state: MutableGraphOfTrustState,
}

fn func_create_declaration_thunk(ctx: &ScFuncContext) {
	ctx.log("graphoftrust.funcCreateDeclaration");
	let f = CreateDeclarationContext {
		events:  GraphOfTrustEvents {},
		params: ImmutableCreateDeclarationParams { proxy: params_proxy() },
		state: MutableGraphOfTrustState { proxy: state_proxy() },
	};
	ctx.require(f.params.declaration_type().exists(), "missing mandatory declarationType");
	ctx.require(f.params.object_hash().exists(), "missing mandatory objectHash");
	ctx.require(f.params.signature().exists(), "missing mandatory signature");
	ctx.require(f.params.signor_hash().exists(), "missing mandatory signorHash");
	func_create_declaration(ctx, &f);
	ctx.log("graphoftrust.funcCreateDeclaration ok");
}

pub struct CreateIdentityClaimContext {
	events:  GraphOfTrustEvents,
	params: ImmutableCreateIdentityClaimParams,
	state: MutableGraphOfTrustState,
}

fn func_create_identity_claim_thunk(ctx: &ScFuncContext) {
	ctx.log("graphoftrust.funcCreateIdentityClaim");
	let f = CreateIdentityClaimContext {
		events:  GraphOfTrustEvents {},
		params: ImmutableCreateIdentityClaimParams { proxy: params_proxy() },
		state: MutableGraphOfTrustState { proxy: state_proxy() },
	};
	ctx.require(f.params.identifier().exists(), "missing mandatory identifier");
	ctx.require(f.params.public_key().exists(), "missing mandatory publicKey");
	ctx.require(f.params.signature().exists(), "missing mandatory signature");
	ctx.require(f.params.validation_url().exists(), "missing mandatory validationUrl");
	func_create_identity_claim(ctx, &f);
	ctx.log("graphoftrust.funcCreateIdentityClaim ok");
}

pub struct InitContext {
	events:  GraphOfTrustEvents,
	params: ImmutableInitParams,
	state: MutableGraphOfTrustState,
}

fn func_init_thunk(ctx: &ScFuncContext) {
	ctx.log("graphoftrust.funcInit");
	let f = InitContext {
		events:  GraphOfTrustEvents {},
		params: ImmutableInitParams { proxy: params_proxy() },
		state: MutableGraphOfTrustState { proxy: state_proxy() },
	};
	func_init(ctx, &f);
	ctx.log("graphoftrust.funcInit ok");
}

pub struct SetIdentifierContext {
	events:  GraphOfTrustEvents,
	params: ImmutableSetIdentifierParams,
	state: MutableGraphOfTrustState,
}

fn func_set_identifier_thunk(ctx: &ScFuncContext) {
	ctx.log("graphoftrust.funcSetIdentifier");
	let f = SetIdentifierContext {
		events:  GraphOfTrustEvents {},
		params: ImmutableSetIdentifierParams { proxy: params_proxy() },
		state: MutableGraphOfTrustState { proxy: state_proxy() },
	};
	ctx.require(f.params.identifier().exists(), "missing mandatory identifier");
	func_set_identifier(ctx, &f);
	ctx.log("graphoftrust.funcSetIdentifier ok");
}

pub struct SetOwnerContext {
	events:  GraphOfTrustEvents,
	params: ImmutableSetOwnerParams,
	state: MutableGraphOfTrustState,
}

fn func_set_owner_thunk(ctx: &ScFuncContext) {
	ctx.log("graphoftrust.funcSetOwner");
	let f = SetOwnerContext {
		events:  GraphOfTrustEvents {},
		params: ImmutableSetOwnerParams { proxy: params_proxy() },
		state: MutableGraphOfTrustState { proxy: state_proxy() },
	};

	// current owner of this smart contract
	let access = f.state.owner();
	ctx.require(access.exists(), "access not set: owner");
	ctx.require(ctx.caller() == access.value(), "no permission");

	ctx.require(f.params.owner().exists(), "missing mandatory owner");
	func_set_owner(ctx, &f);
	ctx.log("graphoftrust.funcSetOwner ok");
}

pub struct SetPublicKeyContext {
	events:  GraphOfTrustEvents,
	params: ImmutableSetPublicKeyParams,
	state: MutableGraphOfTrustState,
}

fn func_set_public_key_thunk(ctx: &ScFuncContext) {
	ctx.log("graphoftrust.funcSetPublicKey");
	let f = SetPublicKeyContext {
		events:  GraphOfTrustEvents {},
		params: ImmutableSetPublicKeyParams { proxy: params_proxy() },
		state: MutableGraphOfTrustState { proxy: state_proxy() },
	};
	ctx.require(f.params.public_key().exists(), "missing mandatory publicKey");
	func_set_public_key(ctx, &f);
	ctx.log("graphoftrust.funcSetPublicKey ok");
}

pub struct SetSignatureContext {
	events:  GraphOfTrustEvents,
	params: ImmutableSetSignatureParams,
	state: MutableGraphOfTrustState,
}

fn func_set_signature_thunk(ctx: &ScFuncContext) {
	ctx.log("graphoftrust.funcSetSignature");
	let f = SetSignatureContext {
		events:  GraphOfTrustEvents {},
		params: ImmutableSetSignatureParams { proxy: params_proxy() },
		state: MutableGraphOfTrustState { proxy: state_proxy() },
	};
	ctx.require(f.params.signature().exists(), "missing mandatory signature");
	func_set_signature(ctx, &f);
	ctx.log("graphoftrust.funcSetSignature ok");
}

pub struct SetValidationUrlContext {
	events:  GraphOfTrustEvents,
	params: ImmutableSetValidationUrlParams,
	state: MutableGraphOfTrustState,
}

fn func_set_validation_url_thunk(ctx: &ScFuncContext) {
	ctx.log("graphoftrust.funcSetValidationUrl");
	let f = SetValidationUrlContext {
		events:  GraphOfTrustEvents {},
		params: ImmutableSetValidationUrlParams { proxy: params_proxy() },
		state: MutableGraphOfTrustState { proxy: state_proxy() },
	};
	ctx.require(f.params.validation_url().exists(), "missing mandatory validationUrl");
	func_set_validation_url(ctx, &f);
	ctx.log("graphoftrust.funcSetValidationUrl ok");
}

pub struct GetDeclarationsContext {
	results: MutableGetDeclarationsResults,
	state: ImmutableGraphOfTrustState,
}

fn view_get_declarations_thunk(ctx: &ScViewContext) {
	ctx.log("graphoftrust.viewGetDeclarations");
	let f = GetDeclarationsContext {
		results: MutableGetDeclarationsResults { proxy: results_proxy() },
		state: ImmutableGraphOfTrustState { proxy: state_proxy() },
	};
	view_get_declarations(ctx, &f);
	ctx.results(&f.results.proxy.kv_store);
	ctx.log("graphoftrust.viewGetDeclarations ok");
}

pub struct GetGraphOfTrustInfoContext {
	results: MutableGetGraphOfTrustInfoResults,
	state: ImmutableGraphOfTrustState,
}

fn view_get_graph_of_trust_info_thunk(ctx: &ScViewContext) {
	ctx.log("graphoftrust.viewGetGraphOfTrustInfo");
	let f = GetGraphOfTrustInfoContext {
		results: MutableGetGraphOfTrustInfoResults { proxy: results_proxy() },
		state: ImmutableGraphOfTrustState { proxy: state_proxy() },
	};
	view_get_graph_of_trust_info(ctx, &f);
	ctx.results(&f.results.proxy.kv_store);
	ctx.log("graphoftrust.viewGetGraphOfTrustInfo ok");
}

pub struct GetIdentityClaimsContext {
	results: MutableGetIdentityClaimsResults,
	state: ImmutableGraphOfTrustState,
}

fn view_get_identity_claims_thunk(ctx: &ScViewContext) {
	ctx.log("graphoftrust.viewGetIdentityClaims");
	let f = GetIdentityClaimsContext {
		results: MutableGetIdentityClaimsResults { proxy: results_proxy() },
		state: ImmutableGraphOfTrustState { proxy: state_proxy() },
	};
	view_get_identity_claims(ctx, &f);
	ctx.results(&f.results.proxy.kv_store);
	ctx.log("graphoftrust.viewGetIdentityClaims ok");
}

pub struct GetOwnerContext {
	results: MutableGetOwnerResults,
	state: ImmutableGraphOfTrustState,
}

fn view_get_owner_thunk(ctx: &ScViewContext) {
	ctx.log("graphoftrust.viewGetOwner");
	let f = GetOwnerContext {
		results: MutableGetOwnerResults { proxy: results_proxy() },
		state: ImmutableGraphOfTrustState { proxy: state_proxy() },
	};
	view_get_owner(ctx, &f);
	ctx.results(&f.results.proxy.kv_store);
	ctx.log("graphoftrust.viewGetOwner ok");
}

pub struct GetSignatureInfoContext {
	results: MutableGetSignatureInfoResults,
	state: ImmutableGraphOfTrustState,
}

fn view_get_signature_info_thunk(ctx: &ScViewContext) {
	ctx.log("graphoftrust.viewGetSignatureInfo");
	let f = GetSignatureInfoContext {
		results: MutableGetSignatureInfoResults { proxy: results_proxy() },
		state: ImmutableGraphOfTrustState { proxy: state_proxy() },
	};
	view_get_signature_info(ctx, &f);
	ctx.results(&f.results.proxy.kv_store);
	ctx.log("graphoftrust.viewGetSignatureInfo ok");
}
