// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]

use wasmlib::*;
use crate::*;

pub struct CreateDeclarationCall {
	pub func: ScFunc,
	pub params: MutableCreateDeclarationParams,
}

pub struct CreateIdentityClaimCall {
	pub func: ScFunc,
	pub params: MutableCreateIdentityClaimParams,
}

pub struct InitCall {
	pub func: ScInitFunc,
	pub params: MutableInitParams,
}

pub struct SetIdentifierCall {
	pub func: ScFunc,
	pub params: MutableSetIdentifierParams,
}

pub struct SetOwnerCall {
	pub func: ScFunc,
	pub params: MutableSetOwnerParams,
}

pub struct SetPublicKeyCall {
	pub func: ScFunc,
	pub params: MutableSetPublicKeyParams,
}

pub struct SetSignatureCall {
	pub func: ScFunc,
	pub params: MutableSetSignatureParams,
}

pub struct SetValidationUrlCall {
	pub func: ScFunc,
	pub params: MutableSetValidationUrlParams,
}

pub struct GetDeclarationsCall {
	pub func: ScView,
	pub results: ImmutableGetDeclarationsResults,
}

pub struct GetGraphOfTrustInfoCall {
	pub func: ScView,
	pub results: ImmutableGetGraphOfTrustInfoResults,
}

pub struct GetIdentityClaimsCall {
	pub func: ScView,
	pub results: ImmutableGetIdentityClaimsResults,
}

pub struct GetOwnerCall {
	pub func: ScView,
	pub results: ImmutableGetOwnerResults,
}

pub struct GetSignatureInfoCall {
	pub func: ScView,
	pub results: ImmutableGetSignatureInfoResults,
}

pub struct ScFuncs {
}

impl ScFuncs {
    pub fn create_declaration(_ctx: &dyn ScFuncCallContext) -> CreateDeclarationCall {
        let mut f = CreateDeclarationCall {
            func: ScFunc::new(HSC_NAME, HFUNC_CREATE_DECLARATION),
            params: MutableCreateDeclarationParams { proxy: Proxy::nil() },
        };
        ScFunc::link_params(&mut f.params.proxy, &f.func);
        f
    }

    pub fn create_identity_claim(_ctx: &dyn ScFuncCallContext) -> CreateIdentityClaimCall {
        let mut f = CreateIdentityClaimCall {
            func: ScFunc::new(HSC_NAME, HFUNC_CREATE_IDENTITY_CLAIM),
            params: MutableCreateIdentityClaimParams { proxy: Proxy::nil() },
        };
        ScFunc::link_params(&mut f.params.proxy, &f.func);
        f
    }

    pub fn init(_ctx: &dyn ScFuncCallContext) -> InitCall {
        let mut f = InitCall {
            func: ScInitFunc::new(HSC_NAME, HFUNC_INIT),
            params: MutableInitParams { proxy: Proxy::nil() },
        };
        ScInitFunc::link_params(&mut f.params.proxy, &f.func);
        f
    }

    pub fn set_identifier(_ctx: &dyn ScFuncCallContext) -> SetIdentifierCall {
        let mut f = SetIdentifierCall {
            func: ScFunc::new(HSC_NAME, HFUNC_SET_IDENTIFIER),
            params: MutableSetIdentifierParams { proxy: Proxy::nil() },
        };
        ScFunc::link_params(&mut f.params.proxy, &f.func);
        f
    }

    pub fn set_owner(_ctx: &dyn ScFuncCallContext) -> SetOwnerCall {
        let mut f = SetOwnerCall {
            func: ScFunc::new(HSC_NAME, HFUNC_SET_OWNER),
            params: MutableSetOwnerParams { proxy: Proxy::nil() },
        };
        ScFunc::link_params(&mut f.params.proxy, &f.func);
        f
    }

    pub fn set_public_key(_ctx: &dyn ScFuncCallContext) -> SetPublicKeyCall {
        let mut f = SetPublicKeyCall {
            func: ScFunc::new(HSC_NAME, HFUNC_SET_PUBLIC_KEY),
            params: MutableSetPublicKeyParams { proxy: Proxy::nil() },
        };
        ScFunc::link_params(&mut f.params.proxy, &f.func);
        f
    }

    pub fn set_signature(_ctx: &dyn ScFuncCallContext) -> SetSignatureCall {
        let mut f = SetSignatureCall {
            func: ScFunc::new(HSC_NAME, HFUNC_SET_SIGNATURE),
            params: MutableSetSignatureParams { proxy: Proxy::nil() },
        };
        ScFunc::link_params(&mut f.params.proxy, &f.func);
        f
    }

    pub fn set_validation_url(_ctx: &dyn ScFuncCallContext) -> SetValidationUrlCall {
        let mut f = SetValidationUrlCall {
            func: ScFunc::new(HSC_NAME, HFUNC_SET_VALIDATION_URL),
            params: MutableSetValidationUrlParams { proxy: Proxy::nil() },
        };
        ScFunc::link_params(&mut f.params.proxy, &f.func);
        f
    }

    pub fn get_declarations(_ctx: &dyn ScViewCallContext) -> GetDeclarationsCall {
        let mut f = GetDeclarationsCall {
            func: ScView::new(HSC_NAME, HVIEW_GET_DECLARATIONS),
            results: ImmutableGetDeclarationsResults { proxy: Proxy::nil() },
        };
        ScView::link_results(&mut f.results.proxy, &f.func);
        f
    }

    pub fn get_graph_of_trust_info(_ctx: &dyn ScViewCallContext) -> GetGraphOfTrustInfoCall {
        let mut f = GetGraphOfTrustInfoCall {
            func: ScView::new(HSC_NAME, HVIEW_GET_GRAPH_OF_TRUST_INFO),
            results: ImmutableGetGraphOfTrustInfoResults { proxy: Proxy::nil() },
        };
        ScView::link_results(&mut f.results.proxy, &f.func);
        f
    }

    pub fn get_identity_claims(_ctx: &dyn ScViewCallContext) -> GetIdentityClaimsCall {
        let mut f = GetIdentityClaimsCall {
            func: ScView::new(HSC_NAME, HVIEW_GET_IDENTITY_CLAIMS),
            results: ImmutableGetIdentityClaimsResults { proxy: Proxy::nil() },
        };
        ScView::link_results(&mut f.results.proxy, &f.func);
        f
    }

    pub fn get_owner(_ctx: &dyn ScViewCallContext) -> GetOwnerCall {
        let mut f = GetOwnerCall {
            func: ScView::new(HSC_NAME, HVIEW_GET_OWNER),
            results: ImmutableGetOwnerResults { proxy: Proxy::nil() },
        };
        ScView::link_results(&mut f.results.proxy, &f.func);
        f
    }

    pub fn get_signature_info(_ctx: &dyn ScViewCallContext) -> GetSignatureInfoCall {
        let mut f = GetSignatureInfoCall {
            func: ScView::new(HSC_NAME, HVIEW_GET_SIGNATURE_INFO),
            results: ImmutableGetSignatureInfoResults { proxy: Proxy::nil() },
        };
        ScView::link_results(&mut f.results.proxy, &f.func);
        f
    }
}
