// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]
#![allow(unused_imports)]

use wasmlib::*;
use crate::*;

#[derive(Clone)]
pub struct ImmutableCreateDeclarationParams {
	pub(crate) proxy: Proxy,
}

impl ImmutableCreateDeclarationParams {
    pub fn declaration_type(&self) -> ScImmutableString {
		ScImmutableString::new(self.proxy.root(PARAM_DECLARATION_TYPE))
	}

    pub fn object_hash(&self) -> ScImmutableHash {
		ScImmutableHash::new(self.proxy.root(PARAM_OBJECT_HASH))
	}

    pub fn signature(&self) -> ScImmutableString {
		ScImmutableString::new(self.proxy.root(PARAM_SIGNATURE))
	}

    pub fn signor_hash(&self) -> ScImmutableHash {
		ScImmutableHash::new(self.proxy.root(PARAM_SIGNOR_HASH))
	}
}

#[derive(Clone)]
pub struct MutableCreateDeclarationParams {
	pub(crate) proxy: Proxy,
}

impl MutableCreateDeclarationParams {
    pub fn declaration_type(&self) -> ScMutableString {
		ScMutableString::new(self.proxy.root(PARAM_DECLARATION_TYPE))
	}

    pub fn object_hash(&self) -> ScMutableHash {
		ScMutableHash::new(self.proxy.root(PARAM_OBJECT_HASH))
	}

    pub fn signature(&self) -> ScMutableString {
		ScMutableString::new(self.proxy.root(PARAM_SIGNATURE))
	}

    pub fn signor_hash(&self) -> ScMutableHash {
		ScMutableHash::new(self.proxy.root(PARAM_SIGNOR_HASH))
	}
}

#[derive(Clone)]
pub struct ImmutableCreateIdentityClaimParams {
	pub(crate) proxy: Proxy,
}

impl ImmutableCreateIdentityClaimParams {
    pub fn identifier(&self) -> ScImmutableString {
		ScImmutableString::new(self.proxy.root(PARAM_IDENTIFIER))
	}

    pub fn public_key(&self) -> ScImmutableString {
		ScImmutableString::new(self.proxy.root(PARAM_PUBLIC_KEY))
	}

    pub fn signature(&self) -> ScImmutableString {
		ScImmutableString::new(self.proxy.root(PARAM_SIGNATURE))
	}

    pub fn validation_url(&self) -> ScImmutableString {
		ScImmutableString::new(self.proxy.root(PARAM_VALIDATION_URL))
	}
}

#[derive(Clone)]
pub struct MutableCreateIdentityClaimParams {
	pub(crate) proxy: Proxy,
}

impl MutableCreateIdentityClaimParams {
    pub fn identifier(&self) -> ScMutableString {
		ScMutableString::new(self.proxy.root(PARAM_IDENTIFIER))
	}

    pub fn public_key(&self) -> ScMutableString {
		ScMutableString::new(self.proxy.root(PARAM_PUBLIC_KEY))
	}

    pub fn signature(&self) -> ScMutableString {
		ScMutableString::new(self.proxy.root(PARAM_SIGNATURE))
	}

    pub fn validation_url(&self) -> ScMutableString {
		ScMutableString::new(self.proxy.root(PARAM_VALIDATION_URL))
	}
}

#[derive(Clone)]
pub struct ImmutableInitParams {
	pub(crate) proxy: Proxy,
}

impl ImmutableInitParams {
    pub fn owner(&self) -> ScImmutableAgentID {
		ScImmutableAgentID::new(self.proxy.root(PARAM_OWNER))
	}
}

#[derive(Clone)]
pub struct MutableInitParams {
	pub(crate) proxy: Proxy,
}

impl MutableInitParams {
    pub fn owner(&self) -> ScMutableAgentID {
		ScMutableAgentID::new(self.proxy.root(PARAM_OWNER))
	}
}

#[derive(Clone)]
pub struct ImmutableSetIdentifierParams {
	pub(crate) proxy: Proxy,
}

impl ImmutableSetIdentifierParams {
    pub fn identifier(&self) -> ScImmutableString {
		ScImmutableString::new(self.proxy.root(PARAM_IDENTIFIER))
	}
}

#[derive(Clone)]
pub struct MutableSetIdentifierParams {
	pub(crate) proxy: Proxy,
}

impl MutableSetIdentifierParams {
    pub fn identifier(&self) -> ScMutableString {
		ScMutableString::new(self.proxy.root(PARAM_IDENTIFIER))
	}
}

#[derive(Clone)]
pub struct ImmutableSetOwnerParams {
	pub(crate) proxy: Proxy,
}

impl ImmutableSetOwnerParams {
    pub fn owner(&self) -> ScImmutableAgentID {
		ScImmutableAgentID::new(self.proxy.root(PARAM_OWNER))
	}
}

#[derive(Clone)]
pub struct MutableSetOwnerParams {
	pub(crate) proxy: Proxy,
}

impl MutableSetOwnerParams {
    pub fn owner(&self) -> ScMutableAgentID {
		ScMutableAgentID::new(self.proxy.root(PARAM_OWNER))
	}
}

#[derive(Clone)]
pub struct ImmutableSetPublicKeyParams {
	pub(crate) proxy: Proxy,
}

impl ImmutableSetPublicKeyParams {
    pub fn public_key(&self) -> ScImmutableString {
		ScImmutableString::new(self.proxy.root(PARAM_PUBLIC_KEY))
	}
}

#[derive(Clone)]
pub struct MutableSetPublicKeyParams {
	pub(crate) proxy: Proxy,
}

impl MutableSetPublicKeyParams {
    pub fn public_key(&self) -> ScMutableString {
		ScMutableString::new(self.proxy.root(PARAM_PUBLIC_KEY))
	}
}

#[derive(Clone)]
pub struct ImmutableSetSignatureParams {
	pub(crate) proxy: Proxy,
}

impl ImmutableSetSignatureParams {
    pub fn signature(&self) -> ScImmutableString {
		ScImmutableString::new(self.proxy.root(PARAM_SIGNATURE))
	}
}

#[derive(Clone)]
pub struct MutableSetSignatureParams {
	pub(crate) proxy: Proxy,
}

impl MutableSetSignatureParams {
    pub fn signature(&self) -> ScMutableString {
		ScMutableString::new(self.proxy.root(PARAM_SIGNATURE))
	}
}

#[derive(Clone)]
pub struct ImmutableSetValidationUrlParams {
	pub(crate) proxy: Proxy,
}

impl ImmutableSetValidationUrlParams {
    pub fn validation_url(&self) -> ScImmutableString {
		ScImmutableString::new(self.proxy.root(PARAM_VALIDATION_URL))
	}
}

#[derive(Clone)]
pub struct MutableSetValidationUrlParams {
	pub(crate) proxy: Proxy,
}

impl MutableSetValidationUrlParams {
    pub fn validation_url(&self) -> ScMutableString {
		ScMutableString::new(self.proxy.root(PARAM_VALIDATION_URL))
	}
}
