// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]
#![allow(unused_imports)]

use newcontract::*;
use wasmlib::*;

use crate::consts::*;
use crate::params::*;
use crate::results::*;
use crate::state::*;

mod consts;
mod contract;
mod params;
mod results;
mod state;

mod newcontract;

const EXPORT_MAP: ScExportMap = ScExportMap {
    names: &[
    	FUNC_INIT,
    	FUNC_SET_OWNER,
    	VIEW_GET_OWNER,
	],
    funcs: &[
    	func_init_thunk,
    	func_set_owner_thunk,
	],
    views: &[
    	view_get_owner_thunk,
	],
};

#[no_mangle]
fn on_call(index: i32) {
	ScExports::call(index, &EXPORT_MAP);
}

#[no_mangle]
fn on_load() {
    ScExports::export(&EXPORT_MAP);
}

pub struct InitContext {
	params: ImmutableInitParams,
	state: MutablenewcontractState,
}

fn func_init_thunk(ctx: &ScFuncContext) {
	ctx.log("newcontract.funcInit");
	let f = InitContext {
		params: ImmutableInitParams { proxy: params_proxy() },
		state: MutablenewcontractState { proxy: state_proxy() },
	};
	func_init(ctx, &f);
	ctx.log("newcontract.funcInit ok");
}

pub struct SetOwnerContext {
	params: ImmutableSetOwnerParams,
	state: MutablenewcontractState,
}

fn func_set_owner_thunk(ctx: &ScFuncContext) {
	ctx.log("newcontract.funcSetOwner");
	let f = SetOwnerContext {
		params: ImmutableSetOwnerParams { proxy: params_proxy() },
		state: MutablenewcontractState { proxy: state_proxy() },
	};

	// current owner of this smart contract
	let access = f.state.owner();
	ctx.require(access.exists(), "access not set: owner");
	ctx.require(ctx.caller() == access.value(), "no permission");

	ctx.require(f.params.owner().exists(), "missing mandatory owner");
	func_set_owner(ctx, &f);
	ctx.log("newcontract.funcSetOwner ok");
}

pub struct GetOwnerContext {
	results: MutableGetOwnerResults,
	state: ImmutablenewcontractState,
}

fn view_get_owner_thunk(ctx: &ScViewContext) {
	ctx.log("newcontract.viewGetOwner");
	let f = GetOwnerContext {
		results: MutableGetOwnerResults { proxy: results_proxy() },
		state: ImmutablenewcontractState { proxy: state_proxy() },
	};
	view_get_owner(ctx, &f);
	ctx.results(&f.results.proxy.kv_store);
	ctx.log("newcontract.viewGetOwner ok");
}
