// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]
#![allow(unused_imports)]

use wasmlib::*;

use crate::*;

#[derive(Clone)]
pub struct ImmutablenewcontractState {
	pub(crate) proxy: Proxy,
}

impl ImmutablenewcontractState {
    pub fn owner(&self) -> ScImmutableAgentID {
		ScImmutableAgentID::new(self.proxy.root(STATE_OWNER))
	}
}

#[derive(Clone)]
pub struct MutablenewcontractState {
	pub(crate) proxy: Proxy,
}

impl MutablenewcontractState {
    pub fn as_immutable(&self) -> ImmutablenewcontractState {
		ImmutablenewcontractState { proxy: self.proxy.root("") }
	}

    pub fn owner(&self) -> ScMutableAgentID {
		ScMutableAgentID::new(self.proxy.root(STATE_OWNER))
	}
}
